In [0]:
import numpy as np

In [3]:
# Setup for questions 1 and 2
arr1=np.arange(40).reshape(8,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [4]:
# Q1. From arr1 you have to fetch out every alternate column starting from col1
arr1[:, [i for i in range(0, arr1.shape[1], 2)]] # Looping to get alternate columns with range taking steps of 2

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24],
       [25, 27, 29],
       [30, 32, 34],
       [35, 37, 39]])

In [5]:
# Q2. From arr1 fetch an array which would contain {0,2,4} {15,17,19} and {30,32,34} 
arr1[[i for i in range(0, arr1.shape[0], 3)]][:,[i for i in range(0, arr1.shape[1], 2)]] # First looping to get an array with desired rows and then looping over the obtained array to get the desired columns hence getting the final array

array([[ 0,  2,  4],
       [15, 17, 19],
       [30, 32, 34]])

In [6]:
# Setup for question

# Generating a random numpy array of intergers ranging between 1 and 100

arr2=np.random.randint(low=1, high=10000, size=10).reshape(2,5)
arr2

array([[3910, 6673, 9591, 7395, 8305],
       [2575, 7727, 8998, 5040,  231]])

 **Normalization** rescales the values into a range of [0,1]. This might be useful in some cases where all parameters need to have the same positive scale. You have to do this a lot in machine learning for eg you are working with 2 cols, one is total runs scored by a batsman(in the scale of 1000s), and the second is number of matches played by him(in the scale of 10s). The formula for normalization is given below

 Xchanged=(X−Xmin)/(Xmax−Xmin)

In [8]:
# Q3. Write a code to normalize arr2.
xmax = arr2.max() # Maximum Value in array
xmin = arr2.min() # Minimum Value in array
normalizefactor = xmax-xmin
arr2 = np.array([(i-xmin)/normalizefactor for i in np.nditer(arr2)]).reshape(arr2.shape) # normalizing the given array
arr2

array([[0.39305556, 0.68824786, 1.        , 0.76538462, 0.86260684],
       [0.25042735, 0.8008547 , 0.9366453 , 0.51378205, 0.        ]])

In [9]:
np.percentile(arr1,25)

9.75

Missing values are a pain in the a**(sorry for language). But yes trust me.

In [16]:
# Q4. How would you check if your numpy array has some missing values?

array = np.array([1, 4, 6, 26, 2, 62, 5, np.nan, 4, 6, 2, 5])
array2 = np.array([2,2,52])

# array contains a nan value
boolValues = np.isnan(array) # Returns true where nan value is present
print(boolValues.any()) # If this returns true my array contains a nan value

# array2 doesn't contain a nan value
boolValues2 = np.isnan(array2)
print(boolValues2.any()) # Yields False because it doesn't contains a nan value
# Hint: Thoda research karo numpy me existing functions hai

True
False

In [20]:
# Q5. Write a function which will accept 2 arguments.
# First: A 1D numpy array arr
# Second: An integer n {Please make sure n<=len(arr)}

# Output: The output should be the nth largest item out of the array

# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40

def nthlargest(arr, n) :
    arrcpy = np.copy(arr)
    arrcpy.sort()
    return(arrcpy[-n])

arr5 = np.array([3,51,4,6,10,2])
nthlargest(arr5, 2)

10

In [25]:
nthlargest(arr5, 1)

51

In [26]:
nthlargest(arr5, 3)

6